export const BEHAVIORAL_SIGNALS = {
  SHORT_READING_PHASE: "SHORT_READING_PHASE",
  LONG_READING_PHASE: "LONG_READING_PHASE",
  IMMEDIATE_CODING: "IMMEDIATE_CODING",
  FAST_CONVERGENCE: "FAST_CONVERGENCE",
  HEAVY_ITERATION: "HEAVY_ITERATION",
  TRIAL_AND_ERROR_LOOP: "TRIAL_AND_ERROR_LOOP",
  APPROACH_ABANDONMENT: "APPROACH_ABANDONMENT",
  MULTIPLE_REWRITES: "MULTIPLE_REWRITES",
  SINGLE_BUG_FIX: "SINGLE_BUG_FIX",
  REPEATED_FAILURE_LOOP: "REPEATED_FAILURE_LOOP",
  RUNTIME_ERROR_RECOVERY: "RUNTIME_ERROR_RECOVERY",
  COMPILATION_ERROR_RECOVERY: "COMPILATION_ERROR_RECOVERY",
  EDGE_CASE_STRUGGLE: "EDGE_CASE_STRUGGLE",
  LATE_EDGE_CASE_DISCOVERY: "LATE_EDGE_CASE_DISCOVERY",
  EDITORIAL_DEPENDENCY: "EDITORIAL_DEPENDENCY",
  HINT_DEPENDENCY: "HINT_DEPENDENCY",
  DIRECT_SOLUTION: "DIRECT_SOLUTION",
  EXPERIMENTAL_EXPLORATION: "EXPERIMENTAL_EXPLORATION"
} as const

export type BehavioralSignalType =
  (typeof BEHAVIORAL_SIGNALS)[keyof typeof BEHAVIORAL_SIGNALS]

export interface BehavioralSignal {
  signal: BehavioralSignalType
  confidence: number
  evidence: string[]
  generatedAt: number
}
